name       : haskell-githash
version    : 0.1.4.0
release    : 1
source     :
    - https://hackage.haskell.org/package/githash-0.1.4.0/githash-0.1.4.0.tar.gz : c3bb8be2aaf072cea1789dfcb63dc9e0a7fb3fdc80a8f296e75fc3acc1105f67
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compile git revision info into Haskell projects
description: |
    Compile git revision info into Haskell projects
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
